#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
server:
  port: ${SERVER_PORT}
  servlet.context-path: /${artifactId}

management:
  endpoints.web.exposure.include: "*"
  endpoint:
    loggers.enabled: true
    prometheus.enabled: true
    metrics:
      enabled: true
      export.prometheus.enabled: true

spring:
  application.name: ms    
# Spring JPA
  datasource:
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServer2012Dialect
        ddl-auto: update